version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: wp_mysql
    volumes:
      - "/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_passwd
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
  phpfpm:
    depends_on:
      - mysql
    image: my/phpfpm:latest
    container_name: wp_phpfpm
    build: ./phpfpm
    volumes:
      - ".:/var/www/html"
      - "./php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    links:
      - mysql
    restart: always
    extra_hosts:
      - "wordpress.dev:172.18.0.1" 
  nginx_server:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
    image: nginx:latest
    volumes:
      - ".:/var/www/html"
      - "./nginx_server/my_nginx.conf:/etc/nginx/conf.d/default.conf"
    links:
      - phpfpm
    restart: always
