version: '2'
services:

  mysql:
    image: mysql:latest
    volumes:
     - "./mysqldb:/var/lib/mysql"
    container_name: wp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootmysqlpassword 
      MYSQL_DATABASE: yourwordpressdbname
      MYSQL_USER: yourwordpressdbuser
      MYSQL_PASSWORD: yourwordpressdbpass

  nginx_server:
    build: .
    ports:
     - "80:80"
    image: nginx:latest
    volumes:
     - "./nginx_config:/etc/nginx"
    volumes_from:
     - phpfpm
    links:
     - phpfpm
    restart: always

  phpfpm:
    image: my/phpfpm:latest
    container_name: wp_phpfpm
    build: ./phpfpm
    ports:
     - "9000"
    links:
      - mysql
    restart: always
    volumes:
     - "./www:/var/www/html"
    extra_hosts:
      - "fenomena.dev:172.18.0.1" #use your own host
        
